language: python
env:
  - CMD=tests
jobs:
  include:
  - python: "2.7"
    env:
     - CMD=all-tests
     - COVERAGE=true
  - python: "3.7"
  - python: "pypy"
  - python: "pypy3"
  - python: "2.7"
    env: CMD=integration-tests
  - python: "3.7"
    env: CMD=integration-tests

cache:
  pip: true
  directories:
  - google-cloud-sdk
  - redis-git

install:
    - pip install -U setuptools
    - pip install -r requirements/ci.txt

services:
    - redis-server
    - memcached

script: make -f Makefile.tests $CMD
after_success:
  - test $COVERAGE = "true" &&
    coveralls
